version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo "Installing dependencies..."
  #      - sudo apt install openjdk-1.8-jdk

  build:
    commands:
      - echo "Building Spring Boot application..."
      - mvn clean install

artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - start_application.sh
  discard_paths: yes
  name: dms-service