version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk-1.8
    commands:
      - echo "Installing Java 1.8"
      - sudo apt install openjdk-1.8-jdk

  build:
    commands:
      - echo "Building the Java application"
      - mvn clean install

  deploy:
    commands:
      - echo "Deploying the Java application"
      - docker build -t dms-service .
      - docker run -d -p 8085:8085 dms-service